<script setup lang="ts">
import ArrowRight from './icons/Arrow-right.vue'
</script>
<template>
  <section id="token" class="pt-[155px] pb-[70px] bg-[#1D1C3E]">
    <div class="container px-2 lg:px-0">
      <h1
        class="text-[40px] lg:text-[64px] leading-[40px] lg:leading-[87.42px] font-medium text-center text-white"
        data-aos="fade-up"
      >
        $VPN TOKEN
      </h1>
      <p
        class="text-center font text-xl lg:text-[30px] leading-7 lg:leading-[41px] mt-[53px] mb-[70px] text-white"
        data-aos="fade-up"
      >
        $VPN is the native token of the 0xVPN network.
      </p>
      <div class="w-full flex flex-col lg:flex-row gap-8">
        <div
          class="w-full lg:w-[617px] flex justify-center items-center flex-col gap-[53px] h-[722px] bg-[#1B255C] rounded-[15px]"
        >
          <img src="/chart.png" alt="" />
          <div>
            <ul data-aos="fade-up" class="font-medium text-[26px] text-white flex-col gap-[18px]">
              <li class="flex gap-4 items-center">
                <span class="block w-[32px] h-[28px] bg-[#344BFD]"></span>
                CEX & PARTNERSHIP
              </li>
              <li class="flex gap-4 items-center">
                <span class="block w-[32px] h-[28px] bg-[#F68D2B]"></span>
                CEX & PARTNERSHIP
              </li>
              <li class="flex gap-4 items-center">
                <span class="block w-[32px] h-[28px] bg-[#F4A79D]"></span>
                CEX & PARTNERSHIP
              </li>
            </ul>
          </div>
        </div>
        <div>
          <p data-aos="fade-up" class="text-base lg:text-[26px] leading-7 font-normal text-white">
            It is used to pay for the VPN services and to reward the nodes that lend their bandwidth
            to the network.
          </p>
          <p
            data-aos="fade-up"
            class="text-base lg:text-[26px] leading-7 font-normal text-white mt-[11px]"
          >
            You can earn VPN tokens by becoming a node and lending your bandwidth to the network.
          </p>
          <table data-aos="fade-up" class="w-full border border-white mt-[35px] mb-8 text-white">
            <tr>
              <td class="py-8 text-center border border-white font-medium text-base lg:text-[26px]">
                Supply
              </td>
              <td
                class="pl-[30px] py-8 border border-white font-medium text-base lg:text-[26px] pl-2"
              >
                100,000,000 VPN
              </td>
            </tr>
            <tr>
              <td class="py-8 text-center border border-white font-medium text-[26px]">Taxes</td>
              <td class="pl-[30px] py-8 border border-white font-medium text-base lg:text-[26px]">
                5% Buy, 5% Sell
              </td>
            </tr>
            <tr>
              <td class="py-8 text-center border border-white font-medium text-base lg:text-[26px]">
                Team Tokens
              </td>
              <td
                class="pl-[30px] py-8 border border-white font-medium text-base lg:text-[26px] pl-2"
              >
                0%, Fair Launch
              </td>
            </tr>
          </table>
          <p data-aos="fade-up" class="text-base lg:text-[26px] leading-7 font-normal text-white">
            Team starts with 0% of the supply as it operates from revenue generated by the network.
          </p>
          <p
            data-aos="fade-up"
            class="text-base lg:text-[26px] leading-7 font-normal text-white mt-[27px]"
          >
            Uniswap Liquidity Pool tokens have been locked for 2 years, check here.
          </p>
          <div data-aos="fade-up" class="flex flex-col lg:flex-row gap-[21px] mt-[75px]">
            <button
              class="flex items-center py-3 border px-[30px] border-white rounded-[27px] text-base lg:text-xl leading-[26px] justify-between font-medium text-white hover:bg-white hover:text-[#121829] duration-[0.3s] transition-all"
            >
              Buy $VPN Token
              <ArrowRight />
            </button>
            <button
              class="flex items-center max-w-full line-clamp-1 py-3 border px-[30px] bg-[#657FCB] border-white rounded-[27px] text-base lg:text-xl leading-[26px] font-medium text-white0"
            >
              0xf898bae008cd85046431ab0a75f00689d6aa1b1c
            </button>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
